Merge jobs into one file

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -5,6 +5,37 @@ on:
     branches: '*'
 
 jobs:
+  test-development:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Build Docker image
+        run: docker build . --tag api.rutgerpronk.com:${{ github.run_number }} --target development
+
+      - name: Run Docker container
+        run: docker run -d --name test-container api.rutgerpronk.com:${{ github.run_number }}
+
+      - name: Wait for the container to start
+        run: sleep 15
+
+      - name: Check container status
+        run: |
+          set -euo pipefail
+
+          container_status=$(docker inspect -f '{{.State.Status}}' "test-container")
+          container_logs=$(docker logs test-container)
+          if [ "$container_status" != "running" ] || [[ $(echo "$container_status" | tr '[:upper:]' '[:lower:]') == *"error"* ]]; then
+            echo "Container failed to start"
+            echo "$container_logs"
+            exit 1
+          else
+            echo "Container started successfully"
+            echo "$container_logs"
+          fi
+
   test-production:
     runs-on: ubuntu-latest
 
@@ -24,7 +55,7 @@ jobs:
       - name: Check container status
         run: |
           set -euo pipefail
-
+  
           container_status=$(docker inspect -f '{{.State.Status}}' "test-container")
           container_logs=$(docker logs test-container)
           if [ "$container_status" != "running" ] || [[ $(echo "$container_status" | tr '[:upper:]' '[:lower:]') == *"error"* ]]; then
